FROM rockylinux:9

# 1. Installer EPEL et les outils de base
RUN dnf install -y epel-release && dnf clean all

# 2. Installation des dépendances + Reset root
RUN dnf install -y \
    openssh-server \
    openssh-clients \
    passwd \
    gcc \
    make \
    pam-devel \
    libcurl-devel \
    pamtester \
    && ssh-keygen -A \
    && dnf clean all \
    && echo 'root:root' | chpasswd \
    && usermod -U root

# 4. Injection de la configuration SSHD (Guillemets refermées + Destination)
RUN rm -f /etc/ssh/sshd_config.d/*.conf && \
    printf "Port 22\n\
Protocol 2\n\
PermitRootLogin yes\n\
StrictModes no\n\
PubkeyAuthentication yes\n\
AuthorizedKeysFile .ssh/authorized_keys\n\
PasswordAuthentication yes\n\
KbdInteractiveAuthentication yes\n\
UsePAM yes\n" > /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]