FROM golang:latest

# Set the working directory
WORKDIR /go/src/app

# Update, install dependencies, and USB/FIDO2 tools
RUN apt-get update && apt-get install -y \
    libfido2-dev libudev-dev usbutils fido2-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Go tools for development and testing
RUN go install golang.org/x/tools/gopls@latest \
    && go install github.com/cweill/gotests/...@latest \
    && go install github.com/fatih/gomodifytags@latest \
    && go install github.com/josharian/impl@latest \
    && go install github.com/haya14busa/goplay/cmd/goplay@latest \
    && go install github.com/go-delve/delve/cmd/dlv@latest \
    && go install honnef.co/go/tools/cmd/staticcheck@latest

# Install go-libfido2 (library for FIDO2 key interactions)
RUN go install github.com/keys-pub/go-libfido2@latest

CMD ["tail", "-f", "/dev/null"]
